/skill mbuff 暗尘弥散 驱夜断愁
/skill tbufftime 怖畏暗刑<0.6 怖畏暗刑
/skill tnobuff 怖畏暗刑 怖畏暗刑
/skill mbuff 冥月渡心 银月斩
/skill moon >99 净世破魔击
/skill moon moon>99&sun<99 光明相
/skill moon sun>99&moon<99 光明相
/skill sun >59 伏明众生
/skill moon >59 冥月渡心
/skill moon sun>99&moon<60 生死劫 
/skill moon sun>70&moon>70 烈日斩
/skill sun >99 净世破魔击